#端口
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

#编码
spring:
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  #数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/scutmall?characterEncoding=UTF8&useSSL=false&serverTimezone=GMT
      username: root
      password: 7887227
      #初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 10
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query-timeout: 60000
      validation-query: SELECT 1 FROM DUAL
      #打开PSCache,并且制定每个链接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  #邮件
  mail:
    host: smtp.qq.com
    username: 1145054472@qq.com
    password: liubin7887227
    default-encoding: UTF-8
  #文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#mybatis路径
mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

mail:
  fromMail:
    addr: 1145054472@qq.com
#日志
logging:
  path: /data/app/bookstore/log/
  level:
    root: info

