package com.scutj2ee.bookstore.dao;

import com.scutj2ee.bookstore.entity.BookCategory;
import java.util.List;

public interface BookCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_category
     *
     * @mbg.generated
     */
    int insert(BookCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_category
     *
     * @mbg.generated
     */
    BookCategory selectByPrimaryKey(Integer cateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_category
     *
     * @mbg.generated
     */
    List<BookCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BookCategory record);
}