package com.scutj2ee.bookstore.dao;

import com.scutj2ee.bookstore.entity.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * create by: Kobe
     * description:更新用户信息
     * create time: 10:41 2019/4/25
     * @return
     */
    int updateUser(User user);
}